export const misData = [
  {
    candId: "CAN-7634",
    name: "Priya Nair",
    email: "aarav.sharma@gmail.com",
    phone: "+91 8548791545",
    hr: "Priya Sharma",
    hrEmail: "Priya.Sharma@Hrmail.Com",
    status: "On Hold",
    permanentAddress: "Bangalore, Karnataka",
    presentAddress: "Same As Permanent",
    drivingLicense: "Failed",
    passport: "Verified",
    panCard: "Verified",
    voterId: "Pending",
    employment1: "Verified",
    employment2: "Verified",
    lastEducation: "Verified",
    criminalRecord: "Verified",
    drugTest: "Pending",
  },
  {
    candId: "CAN-4231",
    name: "Aarav Sharma",
    email: "rohan.mehta@gmail.com",
    phone: "+91 8215479354",
    hr: "Rahul Verma",
    hrEmail: "Rahul.Verma@Hrmail.Com",
    status: "Complete",
    permanentAddress: "Hyderabad, Telangana",
    presentAddress: "Chennai, Tamil Nadu",
    drivingLicense: "Verified",
    passport: "Verified",
    panCard: "Verified",
    voterId: "Verified",
    employment1: "Verified",
    employment2: "Verified",
    lastEducation: "Verified",
    criminalRecord: "Verified",
    drugTest: "Verified",
  },
  {
    candId: "CAN-6421",
    name: "Ananya Verma",
    email: "vivaan.kapoor@gmail.com",
    phone: "+91 5412397465",
    hr: "Sneha Reddy",
    hrEmail: "Sneha.Reddy@Hrmail.Com",
    status: "Complete",
   permanentAddress: "Hyderabad, Telangana",
    presentAddress: "Chennai, Tamil Nadu",
    drivingLicense: "Pending",
    passport: "Verified",
    panCard: "Verified",
    voterId: "Verified",
    employment1: "Verified",
    employment2: "Failed",
    lastEducation: "Verified",
    criminalRecord: "Verified",
    drugTest: "Verified",
  },
  {
    candId: "CAN-6543",
    name: "Arjun Patel",
    email: "arjun.patel@gmail.com",
    phone: "+91 5214987301",
    hr: "Amit Joshi",
    hrEmail: "Amit.Joshi@Hrmail.Com",
    status: "Complete",
   permanentAddress: "Hyderabad, Telangana",
    presentAddress: "Chennai, Tamil Nadu",
    drivingLicense: "Verified",
    passport: "Failed",
    panCard: "Verified",
    voterId: "Verified",
    employment1: "Verified",
    employment2: "Verified",
    lastEducation: "Verified",
    criminalRecord: "Pending",
    drugTest: "Verified",
  },
  {
    candId: "CAN-9087",
    name: "Manav Gupta",
    email: "rahul.mishra@gmail.com",
    phone: "+91 5412897434",
    hr: "Kavya Nair",
    hrEmail: "Kavya.Nair@Hrmail.Com",
    status: "Complete",
    permanentAddress: "Hyderabad, Telangana",
    presentAddress: "Chennai, Tamil Nadu",
    drivingLicense: "Verified",
    passport: "Verified",
    panCard: "Verified",
    voterId: "Verified",
    employment1: "Verified",
    employment2: "Verified",
    lastEducation: "Verified",
    criminalRecord: "Verified",
    drugTest: "Failed",
  },
];
